# Generated by Django 4.2.7 on 2024-03-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0025_employeeloanrepaymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=100)),
                ('expense_type', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sac_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_number', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_gstin', models.CharField(max_length=100)),
                ('vendor_gst_type', models.CharField(max_length=100)),
                ('vendor_source_of_supply', models.CharField(max_length=100)),
                ('vendor_billing_address', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_gstin', models.CharField(max_length=100)),
                ('customer_gst_type', models.CharField(max_length=100)),
                ('customer_price_of_supply', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_billing_address', models.TextField()),
                ('note', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
    ]
