# Generated by Django 4.2.7 on 2024-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0028_alter_expense_vendor_source_of_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='customer_billing_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer_gst_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer_gstin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer_price_of_supply',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor_billing_address',
            field=models.TextField(null=True),
        ),
    ]
