# Generated by Django 4.2.7 on 2024-04-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0029_alter_expense_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
