# Generated by Django 4.2.7 on 2024-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0030_alter_expense_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
