# Generated by Django 4.2.7 on 2024-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0031_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='customer_price_of_supply',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
