# Generated by Django 4.2.7 on 2024-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0037_expensehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bankaccno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='checkno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='upi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
